#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2015-2020 Micron Technology, Inc.  All rights reserved.
#
.PHONY: all clean distclean

all:
	@./configure > config.h

clean distclean:
	@rm -rf test.o test.ko test.mod* .test* [Mm]odule* .tmp_versions built* .built*
	@rm -rf config.h Kbuild Makefile

