#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

case $1 in
    configure)
        depmod -A

        modprobe mpool || echo "Failed to load mpool module, run modprobe manually"

        # Clean up if we did a "force install" via /tmp/mpool-force-install
        if [ -f /tmp/mpool-needs-reboot ]; then
            rm -vf /tmp/mpool-force-install
            rm -f /tmp/mpool-needs-reboot
        fi
        ;;

    *)
esac

exit 0
