#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PKG=$(basename ${0%.*})


case $1 in
    remove|purge)
        depmod -a
        ;;

    abort-upgrade)
        modprobe mpool ||:
        ;;

    *)
esac

exit 0
