#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

case $1 in
    remove)
        if [ -d /dev/mpool ]; then
            mpool scan --deactivate >/dev/null 2>&1 ||:
        fi

        if modinfo mpool >/dev/null 2>&1; then
            modprobe -r mpool && return 0
            echo "Failed to unload the mpool kernel module."
            echo "You must manually unload it after uninstall completes."
        fi
        ;;

    *)
esac

exit 0
