#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PKG=$(basename ${0%.*})


case $1 in
    remove)
        if [ -d /dev/mpool ]; then
            mpool scan --deactivate >/dev/null 2>&1 ||:
        fi

        if modinfo mpool >/dev/null 2>&1; then
            modprobe -r mpool
            if [ $? -ne 0 ]; then
                echo "Failed to unload the mpool kernel module."
                echo "You must manually deactivate any activated mpool(s) and" \
                     "unload the module after uninstall completes."
            fi
        fi
        ;;

    *)
esac

exit 0
