#!/usr/bin/perl

#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2015-2020 Micron Technology, Inc.  All rights reserved.
#

# This script checks whether the kernel headers look sane, and returns an
# error if not.
#
# For Fedora, el7 and el6 we do this as follows:
#
# - Check whether kernel-headers is installed
# - Check whether kernel-headers is at the same version as the kernel
#   (or at the same version as KDIR, if that is passed in)
# - Check whether the files that should have been put there by kernel-headers
#   actually match what kernel-headers put there.
#
# Note that when/if we support non-rpm distros, the policy should be the same,
# but the mechanism will differ.
#
# Usage: check_kernel_headers [KDIR]
#
# if KDIR is not provided, we check whether kernel-headers is at the same
# version as the running kernel.
#

if (defined($ARGV[0])) {
    $uname = $ARGV[0];
    print "Checking kernel headers against $uname\n";
}
else {
    $uname = `uname -r`;
    chomp($uname);
    print "Checking kernel-headers against running kernel ($uname)\n";
}

$uname =~ s/.debug$//g;

@lines = `rpm -qi kernel-headers`;
$rc = $?;
if ($rc) {
    print "Error: perhaps kernel-headers is not installed?\n";
    exit $rc >> 8
}

#
# Parse the rpm version from the 'rpm -qi' output
#
foreach $line (@lines) {
    ($tag, $ver) = split(/:/, $line);
    chomp($ver);
    $ver =~ s/^\s+//; # trim leading whitespace
    $ver =~ s/\s+.*$//;
    if ($tag =~ /^Version/) {
        $fullver = $ver;
    }
    elsif ($tag =~ /^Release/) {
        $fullver = "$fullver-$ver";
    }
    elsif ($tag =~ /^Architecture/) {
        $fullver = "$fullver.$ver";
        $arch_found = true;
    }
}

if (!$arch_found) {
    # on el6, rpm -qi does not include the Architecture
    $arch = `arch`;
    $fullver = "$fullver.$arch";
}

# remove any white space
$fullver =~ s/\s+//g;

sub err_out {
    print "Error: $_[0]\n";
    print "Likely resolution:\n";
    print "'dnf reinstall kernel-headers' (s/dnf/yum on older systems)\n\n";
    exit 1;
}

if ($uname ne $fullver) {
    err_out("kernel-headers ($fullver) mismatches KDIR ($uname)\n");
}

@lines = `rpm -V kernel-headers`;
$rc = $?;
if ($rc) {
    err_out("/usr/include does not match kernel-headers; run rpm -V kernel-headers");
}

print "Congratulations: kernel-headers matches\n";
exit 0;
