obj-m = mpool.o

mpool-objs = evc.o init.o mblock.o mclass.o merr.o mlog.o mp.o mpcore_params.o omf.o pd.o pmd.o sb.o smap.o upgrade.o mpctl.o mcache.o mpctl_sys.o mpctl_reap.o mdc.o

ccflags-y += -Wall
ccflags-y += -Werror
ccflags-y += -Wlogical-op
ccflags-y += -Wuninitialized
ccflags-y += -Wmaybe-uninitialized
ccflags-y += -Wextra

ccflags-y += -Wno-missing-field-initializers
ccflags-y += -Wno-unused-parameter

ccflags-y += -I$M -I$M/include -I$M/../include
