obj-m = mpool.o

mpool-objs = init.o mblock.o mclass.o merr.o mlog_utils.o mlog.o mdc.o omf.o pd.o pmd_obj.o pmd.o sb.o smap.o upgrade.o mpcore.o mp.o mpctl.o mcache.o sysfs.o reaper.o

ccflags-y += -Wall
ccflags-y += -Werror
ccflags-y += -Wlogical-op
ccflags-y += -Wuninitialized
ccflags-y += -Wmaybe-uninitialized
ccflags-y += -Wextra

ccflags-y += -Wno-missing-field-initializers
ccflags-y += -Wno-unused-parameter

ccflags-y += -I$M -I$M/include -I$M/../include
